"""empty message

Revision ID: 354dc0a5334e
Revises: dd24bce84ed1
Create Date: 2024-09-19 15:39:19.412489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354dc0a5334e'
down_revision = 'dd24bce84ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pin_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_salt', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pin_info', schema=None) as batch_op:
        batch_op.drop_column('pin_salt')

    # ### end Alembic commands ###
