"""empty message

Revision ID: 39e292be0ec9
Revises: a265ca3bd731
Create Date: 2022-04-25 19:40:44.064637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e292be0ec9'
down_revision = 'a265ca3bd731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ledger_entry',
                    column_name='aquired_amount',
                    new_column_name='acquired_amount',
                    existing_type=sa.BigInteger(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ledger_entry',
                    column_name='acquired_amount',
                    new_column_name='aquired_amount',
                    existing_type=sa.BigInteger(),
                    existing_nullable=False)
    # ### end Alembic commands ###
