"""empty message

Revision ID: 706698ff9697
Revises: 6e96562b528a
Create Date: 2024-07-12 15:45:22.374006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706698ff9697'
down_revision = '6e96562b528a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rejected_config_signal',
    sa.Column('debtor_id', sa.BigInteger(), nullable=False),
    sa.Column('creditor_id', sa.BigInteger(), nullable=False),
    sa.Column('signal_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('config_ts', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('config_seqnum', sa.Integer(), nullable=False),
    sa.Column('config_flags', sa.Integer(), nullable=False),
    sa.Column('config_data', sa.String(), nullable=False),
    sa.Column('negligible_amount', sa.REAL(), nullable=False),
    sa.Column('rejection_code', sa.String(length=30), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('debtor_id', 'creditor_id', 'signal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rejected_config_signal')
    # ### end Alembic commands ###
