"""empty message

Revision ID: 824705144577
Revises: 39e292be0ec9
Create Date: 2022-08-19 15:50:33.669980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824705144577'
down_revision = '39e292be0ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_config')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_config',
    sa.Column('is_effective', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('min_creditor_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('max_creditor_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.CheckConstraint('(min_creditor_id > 0) OR (max_creditor_id < 0)', name='agent_config_check1'),
    sa.CheckConstraint('is_effective = true', name='agent_config_is_effective_check'),
    sa.CheckConstraint('min_creditor_id <= max_creditor_id', name='agent_config_check'),
    sa.PrimaryKeyConstraint('is_effective', name='agent_config_pkey'),
    comment='Represents the global agent configuration (a singleton). The agent is responsible only for creditor IDs that are within the interval [min_creditor_id, max_creditor_id].'
    )
    # ### end Alembic commands ###
