"""empty message

Revision ID: ced8680106a7
Revises: 5314a555b325
Create Date: 2021-10-13 19:27:34.960583

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ced8680106a7'
down_revision = '5314a555b325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creditor', sa.Column('largest_historic_ledger_entry_id', sa.BigInteger(), server_default='0', nullable=False))
    op.alter_column('ledger_entry', 'creation_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('ledger_entry', 'transfer_number',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('log_entry', 'creation_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('log_entry', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('log_entry', 'data_error_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('log_entry', 'data_finalized_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('log_entry', 'data_next_entry_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('log_entry', 'data_principal',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('log_entry', 'debtor_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('log_entry', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='NULL has the same meaning as FALSE.')
    op.alter_column('log_entry', 'object_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('log_entry', 'object_type_hint',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('log_entry', 'object_update_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('log_entry', 'object_uri',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('log_entry', 'transfer_number',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('log_entry', 'transfer_uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log_entry', 'transfer_uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('log_entry', 'transfer_number',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('log_entry', 'object_uri',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('log_entry', 'object_update_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('log_entry', 'object_type_hint',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('log_entry', 'object_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('log_entry', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='NULL has the same meaning as FALSE.')
    op.alter_column('log_entry', 'debtor_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('log_entry', 'data_principal',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('log_entry', 'data_next_entry_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('log_entry', 'data_finalized_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('log_entry', 'data_error_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('log_entry', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('log_entry', 'creation_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('ledger_entry', 'transfer_number',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('ledger_entry', 'creation_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('creditor', 'largest_historic_ledger_entry_id')
    # ### end Alembic commands ###
