"""empty message

Revision ID: d98019373169
Revises: 354dc0a5334e
Create Date: 2025-05-26 15:57:31.066413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98019373169'
down_revision = '354dc0a5334e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_exchange', schema=None) as batch_op:
        batch_op.drop_constraint('account_exchange_creditor_id_peg_debtor_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'account_exchange', ['creditor_id', 'peg_debtor_id'], ['creditor_id', 'debtor_id'], initially='DEFERRED', deferrable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_exchange', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('account_exchange_creditor_id_peg_debtor_id_fkey', 'account_exchange', ['creditor_id', 'peg_debtor_id'], ['creditor_id', 'debtor_id'])

    # ### end Alembic commands ###
