"""empty message

Revision ID: ff97ba125d5d
Revises: 4e310d9db669
Create Date: 2024-05-14 17:22:39.475418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff97ba125d5d'
down_revision = '4e310d9db669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prepare_transfer_signal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_interest_rate_ts', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.drop_column('min_interest_rate')

    with op.batch_alter_table('running_transfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_interest_rate_ts', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.drop_column('min_interest_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('running_transfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_interest_rate', sa.REAL(), autoincrement=False, nullable=False))
        batch_op.drop_column('final_interest_rate_ts')

    with op.batch_alter_table('prepare_transfer_signal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_interest_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('final_interest_rate_ts')

    # ### end Alembic commands ###
